version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reddit_db
    ports:
      - 6500:5432
    volumes:
      - ./.postgres-files/:/var/lib/postgresql/data/